nkf -w -Lu --overwrite ./a.php
nkf -w -Lu --overwrite ./ao.php
nkf -w -Lu --overwrite ./asp_tags_test.php
nkf -w -Lu --overwrite ./bang_avg.php
nkf -w -Lu --overwrite ./br.php
nkf -w -Lu --overwrite ./calendar.php
nkf -w -Lu --overwrite ./client.php
nkf -w -Lu --overwrite ./comment.php
nkf -w -Lu --overwrite ./d1.php
nkf -w -Lu --overwrite ./data/db_info.php
nkf -w -Lu --overwrite ./db_info.php
nkf -w -Lu --overwrite ./die.php
nkf -w -Lu --overwrite ./do_while.php
nkf -w -Lu --overwrite ./double_quotation.php
nkf -w -Lu --overwrite ./font.php
nkf -w -Lu --overwrite ./font_style.php
nkf -w -Lu --overwrite ./for.php
nkf -w -Lu --overwrite ./for_variation.php
nkf -w -Lu --overwrite ./fukumu.php
nkf -w -Lu --overwrite ./get_okuri.html
nkf -w -Lu --overwrite ./get_okuri2.html
nkf -w -Lu --overwrite ./get_uke.php
nkf -w -Lu --overwrite ./get_uke2.php
nkf -w -Lu --overwrite ./hairetu.php
nkf -w -Lu --overwrite ./hensu.php
nkf -w -Lu --overwrite ./here.php
nkf -w -Lu --overwrite ./hidden.html
nkf -w -Lu --overwrite ./hizuke.php
nkf -w -Lu --overwrite ./host_disp.php
nkf -w -Lu --overwrite ./hr.php
nkf -w -Lu --overwrite ./idou.php
nkf -w -Lu --overwrite ./if.php
nkf -w -Lu --overwrite ./if2.php
nkf -w -Lu --overwrite ./img.php
nkf -w -Lu --overwrite ./info.php
nkf -w -Lu --overwrite ./input_radio.html
nkf -w -Lu --overwrite ./input_submit.html
nkf -w -Lu --overwrite ./input_text.html
nkf -w -Lu --overwrite ./join.php
nkf -w -Lu --overwrite ./kaigyo.php
nkf -w -Lu --overwrite ./kantan.html
nkf -w -Lu --overwrite ./kantan_delete.php
nkf -w -Lu --overwrite ./kantan_delete2.php
nkf -w -Lu --overwrite ./kantan_insert.php
nkf -w -Lu --overwrite ./kantan_search.php
nkf -w -Lu --overwrite ./kantan_select.php
nkf -w -Lu --overwrite ./kantan_select2.php
nkf -w -Lu --overwrite ./kantan2.html
nkf -w -Lu --overwrite ./kantan2_syori.php
nkf -w -Lu --overwrite ./keizi.php
nkf -w -Lu --overwrite ./keizi_kanri.php
nkf -w -Lu --overwrite ./keizi_search.php
nkf -w -Lu --overwrite ./keizi_syokika.php
nkf -w -Lu --overwrite ./keizi_top.php
nkf -w -Lu --overwrite ./nl2br.php
nkf -w -Lu --overwrite ./nl2br_nasi.php
nkf -w -Lu --overwrite ./okuri.html
nkf -w -Lu --overwrite ./okuri_anzen.html
nkf -w -Lu --overwrite ./oyatu.php
nkf -w -Lu --overwrite ./pdo_sounyu.php
nkf -w -Lu --overwrite ./pi.php
nkf -w -Lu --overwrite ./pic/oya.gif
nkf -w -Lu --overwrite ./print_echo_1.php
nkf -w -Lu --overwrite ./print_echo_2.php
nkf -w -Lu --overwrite ./print_echo_3.php
nkf -w -Lu --overwrite ./print_echo_4.php
nkf -w -Lu --overwrite ./radio.php
nkf -w -Lu --overwrite ./radio_uke.php
nkf -w -Lu --overwrite ./rensou.php
nkf -w -Lu --overwrite ./seiki.php
nkf -w -Lu --overwrite ./serv_disp.php
nkf -w -Lu --overwrite ./setuzoku.php
nkf -w -Lu --overwrite ./short_open_tag_test.php
nkf -w -Lu --overwrite ./show_tb.php
nkf -w -Lu --overwrite ./shutdown.php
nkf -w -Lu --overwrite ./single_quotation.php
nkf -w -Lu --overwrite ./sounyu.php
nkf -w -Lu --overwrite ./sounyu_hyouzi.php
nkf -w -Lu --overwrite ./switch.php
nkf -w -Lu --overwrite ./tag.html
nkf -w -Lu --overwrite ./tb_list.php
nkf -w -Lu --overwrite ./test.php
nkf -w -Lu --overwrite ./uke.php
nkf -w -Lu --overwrite ./uke_anzen.php
nkf -w -Lu --overwrite ./while.php
nkf -w -Lu --overwrite ./yume.php
nkf -w -Lu --overwrite ./zyouken.php
