nkf -w -Lu --overwrite ./data/db_info.php
nkf -w -Lu --overwrite ./data/desktop.ini
nkf -w -Lu --overwrite ./CHAPTER21/keizi_search.php
nkf -w -Lu --overwrite ./CHAPTER21/keizi_kanri.php
nkf -w -Lu --overwrite ./CHAPTER21/oya.gif
nkf -w -Lu --overwrite ./CHAPTER21/keizi_top.php
nkf -w -Lu --overwrite ./CHAPTER21/yume.php
nkf -w -Lu --overwrite ./CHAPTER21/keizi_syokika.php
nkf -w -Lu --overwrite ./CHAPTER21/keizi.php
nkf -w -Lu --overwrite ./CHAPTER21/db_info.php
nkf -w -Lu --overwrite ./CHAPTER20/okuri.html
nkf -w -Lu --overwrite ./CHAPTER20/kantan_select2.php
nkf -w -Lu --overwrite ./CHAPTER20/kantan_delete2.php
nkf -w -Lu --overwrite ./CHAPTER20/uke.php
nkf -w -Lu --overwrite ./CHAPTER20/uke_anzen.php
nkf -w -Lu --overwrite ./CHAPTER20/okuri_anzen.html
nkf -w -Lu --overwrite ./CHAPTER20/seiki.php
nkf -w -Lu --overwrite ./CHAPTER20/fukumu.php
nkf -w -Lu --overwrite ./CHAPTER20/db_info.php
nkf -w -Lu --overwrite ./CHAPTER19/kantan_delete.php
nkf -w -Lu --overwrite ./CHAPTER19/kantan_select.php
nkf -w -Lu --overwrite ./CHAPTER19/kantan_search.php
nkf -w -Lu --overwrite ./CHAPTER19/kantan_insert.php
nkf -w -Lu --overwrite ./CHAPTER19/kantan2_syori.php
nkf -w -Lu --overwrite ./CHAPTER19/kantan2.html
nkf -w -Lu --overwrite ./CHAPTER19/kantan.html
nkf -w -Lu --overwrite ./CHAPTER19/desktop.ini
nkf -w -Lu --overwrite ./CHAPTER18/bang_avg.php
nkf -w -Lu --overwrite ./CHAPTER18/sounyu_hyouzi.php
nkf -w -Lu --overwrite ./CHAPTER18/sounyu.php
nkf -w -Lu --overwrite ./CHAPTER18/show_tb.php
nkf -w -Lu --overwrite ./CHAPTER18/setuzoku.php
nkf -w -Lu --overwrite ./CHAPTER18/pdo_sounyu.php
nkf -w -Lu --overwrite ./CHAPTER18/die.php
nkf -w -Lu --overwrite ./CHAPTER18/d1.php
nkf -w -Lu --overwrite ./CHAPTER18/d1.gif
nkf -w -Lu --overwrite ./CHAPTER17/tag.html
nkf -w -Lu --overwrite ./CHAPTER17/uke.php
nkf -w -Lu --overwrite ./CHAPTER17/radio_uke.php
nkf -w -Lu --overwrite ./CHAPTER17/radio.php
nkf -w -Lu --overwrite ./CHAPTER17/okuri.html
nkf -w -Lu --overwrite ./CHAPTER17/nl2br_nasi.php
nkf -w -Lu --overwrite ./CHAPTER17/nl2br.php
nkf -w -Lu --overwrite ./CHAPTER17/kaigyo.php
nkf -w -Lu --overwrite ./CHAPTER17/input_text.html
nkf -w -Lu --overwrite ./CHAPTER17/input_submit.html
nkf -w -Lu --overwrite ./CHAPTER17/input_radio.html
nkf -w -Lu --overwrite ./CHAPTER17/img.php
nkf -w -Lu --overwrite ./CHAPTER17/hr.php
nkf -w -Lu --overwrite ./CHAPTER17/hidden.html
nkf -w -Lu --overwrite ./CHAPTER17/here.php
nkf -w -Lu --overwrite ./CHAPTER17/get_uke2.php
nkf -w -Lu --overwrite ./CHAPTER17/get_uke.php
nkf -w -Lu --overwrite ./CHAPTER17/get_okuri2.html
nkf -w -Lu --overwrite ./CHAPTER17/get_okuri.html
nkf -w -Lu --overwrite ./CHAPTER17/font_style.php
nkf -w -Lu --overwrite ./CHAPTER17/font.php
nkf -w -Lu --overwrite ./CHAPTER17/ao.php
nkf -w -Lu --overwrite ./CHAPTER17/a.php
nkf -w -Lu --overwrite ./CHAPTER16/for_variation.php
nkf -w -Lu --overwrite ./CHAPTER16/for.php
nkf -w -Lu --overwrite ./CHAPTER16/do_while.php
nkf -w -Lu --overwrite ./CHAPTER16/double_quotation.php
nkf -w -Lu --overwrite ./CHAPTER16/client.php
nkf -w -Lu --overwrite ./CHAPTER16/calendar.php
nkf -w -Lu --overwrite ./CHAPTER16/hensu.php
nkf -w -Lu --overwrite ./CHAPTER16/hairetu.php
nkf -w -Lu --overwrite ./CHAPTER16/zyouken.php
nkf -w -Lu --overwrite ./CHAPTER16/while.php
nkf -w -Lu --overwrite ./CHAPTER16/switch.php
nkf -w -Lu --overwrite ./CHAPTER16/single_quotation.php
nkf -w -Lu --overwrite ./CHAPTER16/serv_disp.php
nkf -w -Lu --overwrite ./CHAPTER16/rensou.php
nkf -w -Lu --overwrite ./CHAPTER16/pi.php
nkf -w -Lu --overwrite ./CHAPTER16/oyatu.php
nkf -w -Lu --overwrite ./CHAPTER16/join.php
nkf -w -Lu --overwrite ./CHAPTER16/if2.php
nkf -w -Lu --overwrite ./CHAPTER16/if.php
nkf -w -Lu --overwrite ./CHAPTER16/host_disp.php
nkf -w -Lu --overwrite ./CHAPTER16/hizuke.php
nkf -w -Lu --overwrite ./CHAPTER15/yume.php
nkf -w -Lu --overwrite ./CHAPTER15/test.php
nkf -w -Lu --overwrite ./CHAPTER15/shutdown.php
nkf -w -Lu --overwrite ./CHAPTER15/short_open_tag_test.php
nkf -w -Lu --overwrite ./CHAPTER15/print_echo_4.php
nkf -w -Lu --overwrite ./CHAPTER15/print_echo_3.php
nkf -w -Lu --overwrite ./CHAPTER15/print_echo_2.php
nkf -w -Lu --overwrite ./CHAPTER15/print_echo_1.php
nkf -w -Lu --overwrite ./CHAPTER15/info.php
nkf -w -Lu --overwrite ./CHAPTER15/idou.php
nkf -w -Lu --overwrite ./CHAPTER15/comment.php
nkf -w -Lu --overwrite ./CHAPTER15/br.php
nkf -w -Lu --overwrite ./CHAPTER15/asp_tags_test.php
nkf -w -Lu --overwrite ./CHAPTER14/tb1_make.txt
nkf -w -Lu --overwrite ./CHAPTER14/t.csv
nkf -w -Lu --overwrite ./CHAPTER14/sql.txt
nkf -w -Lu --overwrite ./CHAPTER14/out_file.bat
